# Generated by Django 4.0.4 on 2022-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='الاسم',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
