# Generated by Django 4.0.4 on 2022-05-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_الاسم'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='الاسم',
        ),
        migrations.CreateModel(
            name='Applay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=10)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='cv/')),
                ('texteria', models.TextField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
